[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools > 35", "numpy", "cython", "coolprop"]  # PEP 518 specifications.
build-backend = "setuptools.build_meta"
